// <auto-generated />
using CloudLearn.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudLearn.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcademicYearCourse", b =>
                {
                    b.Property<int>("AcademicYearsId")
                        .HasColumnType("int");

                    b.Property<string>("YearCoursesCourseCode")
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("AcademicYearsId", "YearCoursesCourseCode");

                    b.HasIndex("YearCoursesCourseCode");

                    b.ToTable("AcademicYearCourse");
                });

            modelBuilder.Entity("CloudLearn.Shared.Models.AcademicYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("AcademicYears");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Year = "First Year"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Year = "Second Year"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Year = "Third Year"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Year = "Fourth Year"
                        });
                });

            modelBuilder.Entity("CloudLearn.Shared.Models.Course", b =>
                {
                    b.Property<string>("CourseCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EnrollmentKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LecturerUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CourseCode");

                    b.HasIndex("CourseName")
                        .IsUnique();

                    b.HasIndex("LecturerUserId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CloudLearn.Shared.Models.DegreeProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Program")
                        .IsUnique();

                    b.ToTable("DegreePrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Program = "B. Sc. Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Program = "B. Sc. Telecommunications"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Program = "B. Sc. Computer Eng and IT"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Program = "B. Sc. Business and IT"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Program = "B. Sc. Electronic Science"
                        });
                });

            modelBuilder.Entity("CloudLearn.Shared.Models.Lecturer", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LecturerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("LecturerName")
                        .IsUnique();

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("CloudLearn.Shared.Models.Student", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProgramId");

                    b.HasIndex("YearId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CourseDegreeProgram", b =>
                {
                    b.Property<int>("DegreeProgramId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramCoursesCourseCode")
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("DegreeProgramId", "ProgramCoursesCourseCode");

                    b.HasIndex("ProgramCoursesCourseCode");

                    b.ToTable("CourseDegreeProgram");
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<string>("EnrolledCoursesCourseCode")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("EnrolledStudentsUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EnrolledCoursesCourseCode", "EnrolledStudentsUserId");

                    b.HasIndex("EnrolledStudentsUserId");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("AcademicYearCourse", b =>
                {
                    b.HasOne("CloudLearn.Shared.Models.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("AcademicYearsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudLearn.Shared.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("YearCoursesCourseCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudLearn.Shared.Models.Course", b =>
                {
                    b.HasOne("CloudLearn.Shared.Models.Lecturer", "Lecturer")
                        .WithMany("TeachingCourses")
                        .HasForeignKey("LecturerUserId");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("CloudLearn.Shared.Models.Student", b =>
                {
                    b.HasOne("CloudLearn.Shared.Models.DegreeProgram", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudLearn.Shared.Models.AcademicYear", "Year")
                        .WithMany()
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("CourseDegreeProgram", b =>
                {
                    b.HasOne("CloudLearn.Shared.Models.DegreeProgram", null)
                        .WithMany()
                        .HasForeignKey("DegreeProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudLearn.Shared.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("ProgramCoursesCourseCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("CloudLearn.Shared.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("EnrolledCoursesCourseCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudLearn.Shared.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("EnrolledStudentsUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudLearn.Shared.Models.Lecturer", b =>
                {
                    b.Navigation("TeachingCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
